//array con productos
const products = [
    {
      id: 1,
      title: "Botella Flor de la Vida",
      description: "Botella para solarizar",
      price: 1000,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760750/1_gzg7gb.jpg",
      stock: 100,
    },
    {
      id: 2,
      title: "Botella Metatrón",
      description: "Botella para solarizar",
      price: 1000,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760750/2_wvjv6e.jpg",
      stock: 100,
    },
    {
      id: 3,
      title: "Posa Botella Metatrón",
      description: "Para solarización",
      price: 469,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760750/3_x6uhn0.jpg",
      stock: 50,
    },
    {
      id: 4,
      title: "Posa Botella Flor",
      description: "Para solarización",
      price: 469,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760750/4_kkyjrk.jpg",
      stock: 50,
    },
    {
      id: 5,
      title: "Pulsera Metratón",
      description: "Pulsera con energía positiva",
      price: 439,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760751/5_sqfec1.jpg",
      stock: 20,
    },
    {
      id: 6,
      title: "Pulsera Flor de la Vida",
      description: "Pulsera con energía positiva",
      price: 439,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760750/6_acts3h.jpg",
      stock: 20,
    },
    {
      id: 7,
      title: "Vaso cristal azul",
      description: "Capacidad: 600cc",
      price: 969,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760751/7_n3rpm1.jpg",
      stock: 48,
    },
    {
      id: 8,
      title: "Copa cristal azul",
      description: "Capacidad: 600cc",
      price: 1136,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760751/8_gsw4ze.jpg",
      stock: 36,
    },
    {
      id: 9,
      title: "Agua mineral Sola´n de Cabras",
      description: "500 ml - Botella de vidrio",
      price: 533,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760751/9_qfbph3.jpg",
      stock: 12,
    },
    {
      id: 10,
      title: "Agua mineral Sola´n de Cabras",
      description: "750 ml - Botella de vidrio",
      price: 789,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760751/10_ozpuwc.jpg",
      stock: 12,
    },
    {
      id: 11,
      title: "Agua mineral Sola´n de Cabras",
      description: "1000 ml - Botella de vidrio",
      price: 996,
      image: "https://res.cloudinary.com/josefina18/image/upload/v1629760750/11_ma7gjc.jpg",
      stock: 12,
    },
  ]
  export default products;